### ISSUE TITLE
Reset msys2 ci, when openfhe-development v1.2.1 gets posted

### ISSUE THREAD

**Issue by ArseniyKholod** [hpsc-lab/openfhe-julia#58]
From https://github.com/openfheorg/openfhe-development/issues/825#issuecomment-2228993252, issue with compiler should be solved, when v1.2.1 gets posted
To do:
https://github.com/hpsc-lab/openfhe-julia/blob/9fd2a7d7dd7eeefd36e89be19eb44f968095dff4/.github/workflows/ci.yml#L66
And
https://github.com/hpsc-lab/openfhe-julia/blob/9fd2a7d7dd7eeefd36e89be19eb44f968095dff4/.github/workflows/ci.yml#L70

**Comment by sloede** [comment]
@ArseniyKholod With [v1.2.1](https://github.com/openfheorg/openfhe-development/releases/tag/v1.2.1) being released, it would be great if you could start updating our toolchain as well (but no rush, this is not high priority)
