### ISSUE TITLE
Update OpenFHE in Yggdrasil to v1.2.3

### ISSUE THREAD

**Issue by sloede** [hpsc-lab/openfhe-julia#71]
It would be great if you could update the build recipe on Yggdrasil to use the current version of OpenFHE.

**Comment by ArseniyKholod** [comment]
I have updated in the PRs https://github.com/JuliaPackaging/Yggdrasil/pull/9726 and https://github.com/JuliaPackaging/Yggdrasil/pull/9725

They will probably be merged already on Monday

**Comment by sloede** [comment]
Packages have been merged, thank you
